services:
  caddy:
    image: caddy:2.10
    container_name: caddy
    restart: always
    network_mode: host
    volumes:
      - ./caddy/data:/data
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/templates:/srv
  xray:
    image: ghcr.io/xtls/xray-core:25.12.2
    container_name: xray
    user: root
    command: run -c /etc/xray/config.json
    restart: always
    network_mode: host
    volumes:
      - ./xray:/etc/xray
